services:
  nextjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_END_POINT=https://test.poble.com.au
      - PORT=3000
      - HOSTNAME=0.0.0.0
    restart: unless-stopped